# serverless.yml

service: expense-manager-api

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: ap-northeast-1
  timeout: 30
  # TODO ポリシーを指定
  role: arn:aws:iam::718284540539:role/lambda-vpc-role
  vpc:
    securityGroupIds:
      - sg-055e7ceaa59dbe625
    subnetIds:
      - subnet-c2b39e99
      - subnet-e05ba8a8
      - subnet-fa43b9d1

functions:
  #  TODO 共通設定を共通化したい
  accounts:
    handler: controllers/account-controller.getAccounts
    events:
      - http: GET /accounts
        headers:
          Content-Type: "'application/json'"
  getTransactions:
    handler: controllers/transaction-controller.getTransactions
    events:
      - http: GET /transactions
        headers:
          Content-Type: "'application/json'"
  getTransaction:
    handler: controllers/transaction-controller.getTransaction
    events:
      - http: GET /transactions/{transaction_id}
        headers:
          Content-Type: "'application/json'"
  createTransaction:
    handler: controllers/transaction-controller.createTransaction
    events:
      - http: POST /transactions
        headers:
          Content-Type: "'application/json'"
  updateTransaction:
    handler: controllers/transaction-controller.updateTransaction
    events:
      - http: PUT /transactions/{transaction_id}
        headers:
          Content-Type: "'application/json'"

  initDb:
    handler: batch/init-db.init

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin

custom:
  customDomain:
    domainName: api.expense-manager.cloud
    certificateName: 'expense-manager.cloud'
    basePath: ''
    stage: prod
    createRoute53Record: true
#  serverless-offline:
#    httpPort: 4000
#    lambdaPort: 4001