# serverless.yml

service: expense-manager-api

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: ap-northeast-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline