# serverless.yml

service: expense-manager-api

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: ap-northeast-1

functions:
  accounts:
    handler: controllers/account.controller.handler
    events:
      - http: GET /accounts
#  app:
#    handler: index.handler
#    events:
#      - http: ANY /
#      - http: 'ANY {proxy+}'
  dbSync:
    handler: batch/dbSync.handler

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  # カスタムドメインの設定
  customDomain:
    domainName: api.expense-manager.cloud
    certificateName: 'expense-manager.cloud'
    basePath: ''
    stage: prod
    createRoute53Record: true
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4001